# Generated by Django 5.0 on 2024-06-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsportal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article_model",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
    ]
