# Generated by Django 5.0 on 2024-06-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsportal", "0002_alter_article_model_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article_model",
            name="is_trending",
            field=models.BooleanField(default=True),
        ),
    ]
