# Generated by Django 5.0 on 2026-06-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0003_alter_article_model_is_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('homepage_top', 'Homepage Top'), ('homepage_middle', 'Homepage Middle'), ('homepage_bottom', 'Homepage Bottom'), ('article_top', 'Article Top'), ('article_bottom', 'Article Bottom'), ('sidebar', 'Sidebar')], max_length=50)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'priority'],
            },
        ),
    ]
