# Generated by Django 5.0 on 2026-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0004_ad_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_model',
            name='section',
            field=models.CharField(choices=[('homepage_top', 'Homepage Top'), ('homepage_upper_middle', 'Homepage Upper Middle'), ('homepage_middle', 'Homepage Middle'), ('homepage_bottom', 'Homepage Bottom'), ('article_top', 'Article Top'), ('article_bottom', 'Article Bottom'), ('sidebar', 'Sidebar')], max_length=50),
        ),
    ]
